export const GET_PROCEEDINGS_DATES_REQUEST = 'GET_PROCEEDINGS_DATES_REQUEST';
export const GET_PROCEEDINGS_DATES_ERROR = 'GET_PROCEEDINGS_DATES_ERROR';

export const GET_PROCEEDING_BY_DATE_REQUEST = 'GET_PROCEEDING_BY_DATE_REQUEST';
export const GET_PROCEEDING_BY_DATE_ERROR = 'GET_PROCEEDING_BY_DATE_ERROR';