export const UPLOAD_PHOTO_REQUEST = 'UPLOAD_PHOTO_REQUEST';
export const UPLOAD_PHOTO_ERROR = 'UPLOAD_PHOTO_ERROR';

export const CREATE_NEWS_REQUEST = 'CREATE_NEWS_REQUEST';
export const CREATE_NEWS_ERROR = 'CREATE_NEWS_ERROR';

export const GET_ALL_NEWS_REQUEST = 'GET_ALL_NEWS_REQUEST';
export const GET_ALL_NEWS_ERROR = 'GET_ALL_NEWS_ERROR';

export const GET_NEWS_REQUEST = 'GET_NEWS_REQUEST';
export const GET_NEWS_ERROR = 'GET_NEWS_ERROR';

export const EDIT_NEWS_REQUEST = 'EDIT_NEWS_REQUEST';
export const EDIT_NEWS_ERROR = 'EDIT_NEWS_ERROR';

export const DELETE_NEWS_REQUEST = 'DELETE_NEWS_REQUEST';
export const DELETE_NEWS_ERROR = 'DELETE_NEWS_ERROR';