export const GET_PROFILE_USER_REQUEST = "GET_PROFILE_USER_REQUEST";
export const GET_PROFILE_USER_ERROR = "GET_PROFILE_USER_ERROR";

export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';

export const EDIT_USER_REQUEST = 'EDIT_USER_REQUEST';
export const EDIT_USER_ERROR = 'EDIT_USER_ERROR';