
export const GET_STATEMENTS_BY_DATE_REQUEST = 'GET_STATEMENTS_BY_DATE_REQUEST';
export const GET_STATEMENTS_BY_DATE_ERROR = 'GET_STATEMENTS_BY_DATE_ERROR';

export const GET_STATEMENT_REQUEST = 'GET_STATEMENT_REQUEST';
export const GET_STATEMENT_ERROR = 'GET_STATEMENT_ERROR';

export const GET_STATEMENT_TEXT_REQUEST = 'GET_STATEMENT_TEXT_REQUEST';
export const GET_STATEMENT_TEXT_ERROR = 'GET_STATEMENT_TEXT_ERROR';