export const GET_ALL_VOTINGS_REQUEST = 'GET_ALL_VOTINGS_REQUEST';
export const GET_ALL_VOTINGS_ERROR = 'GET_ALL_VOTINGS_ERROR';

export const GET_VOTING_DETAILS_REQUEST = 'GET_VOTING_DETAILS_REQUEST';
export const GET_VOTING_DETAILS_ERROR = 'GET_VOTING_DETAILS_ERROR';

export const SEARCH_VOTINGS_REQUEST = 'SEARCH_VOTINGS_REQUEST';
export const SEARCH_VOTINGS_ERROR = 'SEARCH_VOTINGS_ERROR';

export const GET_VOTES_BY_VOTING_REQUEST = "GET_VOTES_BY_VOTING_REQUEST";
export const GET_VOTES_BY_VOTING_ERROR = "GET_VOTES_BY_VOTING_ERROR";

export const GET_VOTINGS_BY_DATE_REQUEST = 'GET_VOTES_BY_DATE_REQUEST';
export const GET_VOTINGS_BY_DATE_ERROR = 'GET_VOTES_BY_DATE_ERROR';