export const ADD_POST_REQUEST = "ADD_POST_REQUEST";
export const ADD_POST_ERROR = "ADD_POST_ERROR";

export const FETCH_THREADS_REQUEST = "FETCH_THREADS_REQUEST";
export const FETCH_THREADS_ERROR = "FETCH_THREADS_ERROR";

export const FETCH_THREAD_BY_ID_REQUEST = "FETCH_THREAD_BY_ID_REQUEST";
export const FETCH_THREAD_BY_ID_ERROR = "FETCH_THREAD_BY_ID_ERROR";

export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST";
export const ADD_COMMENT_ERROR = "ADD_COMMENT_ERROR";

export const FETCH_COMMENT_BY_THREAD_ID_REQUEST = "FETCH_COMMENT_BY_THREAD_ID_REQUEST";
export const FETCH_COMMENT_BY_THREAD_ID_ERROR = "FETCH_COMMENT_BY_THREAD_ID_ERROR";

export const UPVOTE_COMMENT_REQUEST = "UPVOTE_COMMENT_REQUEST";
export const UPVOTE_COMMENT_ERROR = "UPVOTE_COMMENT_ERROR";

export const DOWNVOTE_COMMENT_REQUEST = "DOWNVOTE_COMMENT_REQUEST";
export const DOWNVOTE_COMMENT_ERROR = "DOWNVOTE_COMMENT_ERROR";

export const UPVOTE_POST_REQUEST = "UPVOTE_POST_REQUEST";
export const UPVOTE_POST_ERROR = "UPVOTE_POST_ERROR";

export const DOWNVOTE_POST_REQUEST = "DOWNVOTE_POST_REQUEST";
export const DOWNVOTE_POST_ERROR = "DOWNVOTE_POST_ERROR";
